=== Kataera/Oracle/Data/Fates/FateData.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" />
  <xs:element name="Fates">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Fate" maxOccurs="unbounded" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Fate">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ID" maxOccurs="1" minOccurs="1" />
        <xs:element ref="Name" maxOccurs="1" minOccurs="1" />
        <xs:element ref="Level" maxOccurs="1" minOccurs="1" />
        <xs:element ref="Type" maxOccurs="1" minOccurs="1" />
        <xs:element ref="OracleSupport" maxOccurs="1" minOccurs="1" />
        <xs:element ref="LandingRadius" maxOccurs="1" minOccurs="0" />
        <xs:element ref="CollectItemId" maxOccurs="1" minOccurs="0" />
        <xs:element ref="NpcId" maxOccurs="1" minOccurs="0" />
        <xs:element ref="PreferredTargetId" maxOccurs="unbounded" minOccurs="0" />
        <xs:element ref="ChainID" maxOccurs="1" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ID">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="100" />
        <xs:maxInclusive value="999" />
        <xs:totalDigits value="3" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Name">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:whiteSpace value="preserve" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Level">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1" />
        <xs:maxInclusive value="60" />
        <xs:totalDigits value="2" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Type">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0" />
        <xs:maxInclusive value="5" />
        <xs:totalDigits value="1" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="OracleSupport">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0" />
        <xs:maxInclusive value="4" />
        <xs:totalDigits value="1" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="LandingRadius">
    <xs:simpleType>
      <xs:restriction base="xs:float">
        <xs:minInclusive value="0.0" />
        <xs:maxInclusive value="1.0" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="CollectItemId" type="xs:integer" />
  <xs:element name="NpcId" type="xs:integer" />
  <xs:element name="PreferredTargetId" type="xs:integer" />
  <xs:element name="ChainID">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="100" />
        <xs:maxInclusive value="999" />
        <xs:totalDigits value="3" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

=== Kataera/Oracle/Data/Fates/FateData.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Fates[

<!-- Fate types -->
<!ENTITY Kill "0">
<!ENTITY Collect "1">
<!ENTITY Escort "2">
<!ENTITY Defence "3">
<!ENTITY Boss "4">
<!ENTITY MegaBoss "5">

<!-- Support levels -->
<!ENTITY FullSupport "0">
<!ENTITY CustomSupport "1">
<!ENTITY Problematic "2">
<!ENTITY Unsupported "3">
<!ENTITY NotInGame "4">

]>

<Fates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="FateData.xsd">
  <Fate>
    <ID>102</ID>
    <Name>aaaa</Name>
    <Level>1</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>104</ID>
    <Name>エリア防衛</Name>
    <Level>1</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>105</ID>
    <Name>山賊砦テスト</Name>
    <Level>1</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>106</ID>
    <Name>収集系テスト</Name>
    <Level>1</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>107</ID>
    <Name>山賊砦ボス</Name>
    <Level>1</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>108</ID>
    <Name>山賊砦味方防衛</Name>
    <Level>1</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>109</ID>
    <Name>りんご集め</Name>
    <Level>1</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>120</ID>
    <Name>Clever Girls</Name>
    <Level>5</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>121</ID>
    <Name>One Enchanted Eve</Name>
    <Level>4</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>122</ID>
    <Name>Sprig Cleaning</Name>
    <Level>30</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>123</ID>
    <Name>Something in the Water</Name>
    <Level>8</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>124</ID>
    <Name>The Sting</Name>
    <Level>11</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>125</ID>
    <Name>Asipatra Attacks</Name>
    <Level>34</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>126</ID>
    <Name>Leader of the Pack</Name>
    <Level>9</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>127</ID>
    <Name>A Mother Scorned</Name>
    <Level>8</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>128</ID>
    <Name>Alux of the Draw</Name>
    <Level>9</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>129</ID>
    <Name>※β1不要：船着場までチョコボの護衛（仮）</Name>
    <Level>10</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>130</ID>
    <Name>エバーシェイドの収穫祭</Name>
    <Level>14</Level>
    <Type>&Collect;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
    <CollectItemId>2000193</CollectItemId>
    <NpcId>0</NpcId>
  </Fate>
  <Fate>
    <ID>131</ID>
    <Name>Lethe on My Mind</Name>
    <Level>10</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>132</ID>
    <Name>※β1不要：採掘場奪取</Name>
    <Level>35</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>133</ID>
    <Name>※β1不要：採掘場奪取</Name>
    <Level>35</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>134</ID>
    <Name>※β1不要：採掘場防衛</Name>
    <Level>35</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>135</ID>
    <Name>※β1不要：採掘場防衛</Name>
    <Level>35</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>136</ID>
    <Name>Training Day</Name>
    <Level>5</Level>
    <Type>&Defence;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>137</ID>
    <Name>Bleeding Green</Name>
    <Level>13</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>138</ID>
    <Name>Tastes Like Chick</Name>
    <Level>10</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>139</ID>
    <Name>Sleep Tight</Name>
    <Level>12</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>140</ID>
    <Name>Spirithold Run</Name>
    <Level>10</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>141</ID>
    <Name>Love Is in the Air</Name>
    <Level>11</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>142</ID>
    <Name>There's Something about Lou</Name>
    <Level>14</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>143</ID>
    <Name>Now I See Bees I Won</Name>
    <Level>11</Level>
    <Type>&Defence;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>144</ID>
    <Name>Royal Rumble</Name>
    <Level>16</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>145</ID>
    <Name>戦場までは何マルム？</Name>
    <Level>19</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>146</ID>
    <Name>※β1不要：シルフの隊長撃破</Name>
    <Level>45</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>147</ID>
    <Name>※β1不要：蜂蜜酒輸送護衛</Name>
    <Level>25</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>148</ID>
    <Name>What a Bee Wants</Name>
    <Level>10</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>149</ID>
    <Name>Stopping the Spread</Name>
    <Level>17</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>150</ID>
    <Name>Jack of All Trades</Name>
    <Level>19</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
    <PreferredTargetId>535</PreferredTargetId>
  </Fate>
  <Fate>
    <ID>151</ID>
    <Name>リトルブリッジの戦い</Name>
    <Level>24</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>152</ID>
    <Name>Protecting the Patch</Name>
    <Level>20</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>153</ID>
    <Name>The Hunted</Name>
    <Level>23</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>154</ID>
    <Name>Eft for Dead</Name>
    <Level>34</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>155</ID>
    <Name>※β1不要：キャラバン護衛</Name>
    <Level>25</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>156</ID>
    <Name>※β1不要：野盗退治</Name>
    <Level>35</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>157</ID>
    <Name>※β1不要：インプ退治</Name>
    <Level>37</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>158</ID>
    <Name>The Negotiators</Name>
    <Level>28</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>159</ID>
    <Name>Breaching the Hive</Name>
    <Level>32</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&Problematic;</OracleSupport>
    <ChainID>160</ChainID>
  </Fate>
  <Fate>
    <ID>160</ID>
    <Name>Clearing the Hive</Name>
    <Level>32</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&Problematic;</OracleSupport>
    <ChainID>162</ChainID>
  </Fate>
  <Fate>
    <ID>161</ID>
    <Name>Defending the Hive</Name>
    <Level>32</Level>
    <Type>&Defence;</Type>
    <OracleSupport>&Problematic;</OracleSupport>
  </Fate>
  <Fate>
    <ID>162</ID>
    <Name>Keeping the Hive</Name>
    <Level>32</Level>
    <Type>&Defence;</Type>
    <OracleSupport>&Problematic;</OracleSupport>
  </Fate>
  <Fate>
    <ID>163</ID>
    <Name>Kickin' It with the Kedtraps</Name>
    <Level>22</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>164</ID>
    <Name>The Coeurl King</Name>
    <Level>29</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>165</ID>
    <Name>※β1不要：騎POP候補</Name>
    <Level>50</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&NotInGame;</OracleSupport>
  </Fate>
  <Fate>
    <ID>166</ID>
    <Name>Another Round</Name>
    <Level>22</Level>
    <Type>&Defence;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>167</ID>
    <Name>Stag Parting</Name>
    <Level>21</Level>
    <Type>&Kill;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>168</ID>
    <Name>Hide and Seek</Name>
    <Level>29</Level>
    <Type>&Collect;</Type>
    <OracleSupport>&Problematic;</OracleSupport>
    <CollectItemId>2000251</CollectItemId>
    <NpcId>526</NpcId>
  </Fate>
  <Fate>
    <ID>169</ID>
    <Name>A Tale of Two-tails</Name>
    <Level>32</Level>
    <Type>&Boss;</Type>
    <OracleSupport>&FullSupport;</OracleSupport>
  </Fate>
  <Fate>
    <ID>170</ID>
